version: '3.7'

services:
  pdftruth_db_master:
    image: bitnami/postgresql:17
    container_name: pdftruth_db_master
    networks:
      - webnet
    ports:
    - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    env_file:
      - .env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes

  pdftruth_db_slave:
    image: bitnami/postgresql:17
    container_name: pdftruth_db_slave
    networks:
      - webnet
    ports:
      - '${DB_PORT_SLAVE}:${DB_PORT}'
    depends_on:
      - pdftruth_db_master
    env_file:
      - .env
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=pdftruth_db_master
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=${DB_PORT}
      - ALLOW_EMPTY_PASSWORD=yes

  pdftruth_app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: base
    container_name: pdftruth_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - webnet
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    depends_on:
      - pdftruth_db_master
      - pdftruth_db_slave
    command:
      - /bin/bash
      - -c
      - |
        yarn run start:dev  

networks:
  webnet:
    driver: bridge

volumes:
  postgresql_master_data:
    driver: local